=== mozotom/mozotom.github.io/tree.dtd
<!ELEMENT root (branch*)>
<!ATTLIST root title CDATA "" >

<!ELEMENT branch (branch*) >
<!ATTLIST branch name CDATA #REQUIRED >
<!ATTLIST branch link CDATA #IMPLIED >
<!ATTLIST branch info CDATA #IMPLIED >
<!ATTLIST branch target CDATA "node" >

=== mozotom/mozotom.github.io/tree.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="tree.xsl"?>
<!DOCTYPE root SYSTEM 'tree.dtd'>

<!-- Copyright Tomasz Mozolewski @2006 -->
<!-- Updated Tomasz Mozolewski @2009 -->
<root title="Tomek's Home Page 2008">
  <branch name="Quick Links">
    <branch link="http://mail.yahoo.com" name="Yahoo Mail" target="_blank" />
    <branch link="http://money.cnn.com/" name="CNN Money" />
    <branch link="http://www.jewishworldreview.com/cols/sowell1.asp" name="Thomas Sowell" />
    <branch link="http://www.dilbert.com/strips/" name="Dilbert" />
    <branch link="http://newsmap.jp/" name="Newsmap" target="_blank" />
    <branch link="https://www.straighttalk.com/CheckBalance" name="StraightTalk" />
    <branch link="http://www.reuters.com/" name="Reuters" />
    <branch link="http://slashdot.org/" name="Slashdot" />
    <branch link="http://www.netflix.com/" name="Netflix" target="_blank" />
    <branch link="http://news.bbc.co.uk/" name="BBC" />
    <branch link="other/TrafficCam40K.html" name="Traffic 40 &amp; K" info="Traffic camera on I64/40 &amp; HW K intersection" />
  </branch>
  <branch name="Me">
    <branch name="Projects">
      <branch name="Presentations">
        <branch link="Presentations/Concurrency%20in%20Java%202011.pdf" name="Concurrency in Java 2011" />
        <branch link="Presentations/Unit%20Testing%202010.pptx" name="Unit Testing 2010" />
        <branch link="Presentations/Java%20Threads%202009.pdf" name="Java Threads 2009" />
      </branch>
      <branch name="vCard Contacts">
        <branch link="http://mozotom.50webs.com/projects/ContactsManager/ContactsDupMerge.html" name="Duplicate Merge" />
        <branch link="http://mozotom.50webs.com/projects/ContactsManager/ContactsEditor.html" name="Online Editor" />
      </branch>
      <branch name="Problem Solution Helpers">
        <branch link="projects/LogicPuzzle.jar" name="LogicPuzzle" />
        <branch link="projects/sudoku/sudoku.html" name="Sudoku" />
      </branch>
      <branch name="Debug util">
        <branch link="projects/ThreadDumpAnalyzer.jar" name="Thread dump analyzer JDK 1.4" />
        <branch link="projects/ThreadSummaryViewer.jar" name="Thread dump viewer" />
        <branch link="projects/ClearPipe.jar" name="Clear Pipe" />
        <branch link="projects/PortScanner.jar" name="Port Scanner" />
        <branch link="projects/ValueTracker.zip" name="Value Tracker" />
        <branch link="projects/ThreadDumpAnalyzer/ThreadDumpAnalyzer.html" name="Thread Dump Analyzer" />
      </branch>
      <branch name="Problem solvers">
        <branch link="projects/PegGame.jar" name="Peg Game" />
      </branch>
      <branch name="GFX">
        <branch link="projects/MosaicMaker.zip" name="Hex Mosaic Maker" />
        <branch link="projects/color.test.zip" name="Monitor Test" />
        <branch link="projects/ScreenTest/ScreenTest.html" name="Screen Test" target="_blank" />
        <branch link="projects/Drawing/drawing.html?q=sample.json" name="Drawing Sample" target="_blank" />
        <branch link="projects/Drawing/drawing.html?q=MasterBath.json" name="Drawing Master Bath" target="_blank" />
      </branch>
      <branch name="Games">
        <branch link="projects/SlideGame.jar" name="Slide Game" />
        <branch link="wii/map.html" name="Wii Sports Resort Island Flyover Map" />
        <branch link="projects/ResetableTimer/options.html" name="Game Timer" target="_blank" />
        <branch link="projects/FlashCards/options.html" name="Math Flash Cards" target="_blank" />
        <branch link="projects/School/2-Math-Add-Sub-20.xls" name="2nd Grade Math - Add Sub 20" />
        <branch link="projects/School/Math.xlsm" name="Math - Add Sub Mult Div 0-9" />
        <branch link="projects/Typing/typing.html" name="Typing Words" />
        <branch link="projects/TypingLetters/typing.html" name="Typing Letters" />
        <branch link="http://10fastfingers.com/text/61065-the-quick-brown-fox-jumps-over-the-lazy-dog" name="Typing Alphabet" />
      </branch>
      <branch name="Web code examples">
        <branch link="projects/pivot-table/pivot-table.xml" name="Pivot Table" />
        <branch link="projects/urlChecker.zip" name="Url Checker (all)" />
        <branch link="projects/WebsiteGrabber.zip" name="Website Grabber" />
      </branch>
      <branch name="Excel Worksheets">
        <branch link="projects/Task_Organizer.xls" name="Task Organizer" />
        <branch link="projects/matchrows.html" name="Table row matching" />
        <branch link="projects/BudgetTemplate.xls" name="Budget Template" />
      </branch>
      <branch name="Encryption">
        <branch link="projects/RSA-AES-GUI-Cipher.html" name="GUI RSA / AES encryption" />
      </branch>
      <branch name="Java">
        <branch link="projects/Log4jDemo.zip" name="Log4j per environment" />
      </branch>
      <branch name="Wood working">
        <branch link="projects/av-shelf.doc" name="Audio / Video Shelf" />
      </branch>
      <branch name="Database and SQL">
        <branch link="projects/business_day_calendar.txt" name="Business Day Calendar" />
      </branch>
      <branch name="Other">
        <branch link="projects/RoboMouse.jar" name="Robo Mouse" />
        <branch link="projects/urlrefresher1/refresher-iframe.html" name="Url Refresher iFrame" />
        <branch link="projects/urlrefresher1/refresher.html" name="Url Refresher Single" />
        <branch link="projects/urlrefresher4/refresher.html" name="Url Refresher Quad" />
      </branch>
      <branch name="Templates">
        <branch link="projects/CanvasTemplate/canvas.html" name="HTML5 Canvas" target="_blank" />
      </branch>
      <branch name="Search engines">
	<branch link="flightsearch/FlightSearch.html" name="Flight Search" />
      </branch>
    </branch>
    <branch name="Photos">
      <branch link="http://www.flickr.com/photos/mozotom/show" name="Cleo &amp; Vicky Flickr" />
      <branch link="http://photo.net/photodb/slideshow?folder_id=518401" name="Cleo &amp; Vicky Photo.net" />
      <branch link="http://www.photo.net/photodb/member-photos?include=all&amp;user_id=857465" name="photo.net" />
      <branch link="http://www.flickr.com/photos/38015967@N04/show/" name="Piotrek" />
      <branch link="http://travel.state.gov/_res/flash/cropper/FIG_cropper.html" name="Passport Photo Crop Tool" />
    </branch>
  </branch>
  <branch name="References">
    <branch name="Java References">
      <branch name="Classes">
        <branch link="http://java.sun.com/javase/6/docs/api/" name="JDK 1.6" />
        <branch link="http://java.sun.com/j2se/1.5.0/docs/api/" name="JDK 1.5.0" />
        <branch link="http://java.sun.com/j2se/1.4/docs/api/" name="JDK 1.4.2" />
        <branch link="http://java.sun.com/j2se/1.3/docs/api/" name="JDK 1.3.1" />
      </branch>
      <branch name="Other">
        <branch link="http://java.sun.com/docs/codeconv/html/CodeConvTOC.doc.html" name="Code Conventions for the Java" />
      </branch>
      <branch name="Imaging">
        <branch link="http://sourceforge.net/projects/jiu/" name="Java Imaging Utilities" />
      </branch>
      <branch name="Sound">
        <branch link="http://www.tritonus.org" name="Tritonus is an implementation of the Java Sound API" />
      </branch>
      <branch name="Troubleshooting">
        <branch link="http://developer.java.sun.com/developer/onlineTraining/Programming/JDCBook/stack.html" name="Analyzing Stack Traces" />
        <branch link="http://developer.java.sun.com/developer/technicalArticles/Programming/Stacktrace/" name="An Introduction to Java Stack Traces" />
      </branch>
      <branch name="Security">
        <branch link="http://java.sun.com/j2se/1.4.2/docs/guide/security/permissions.html" name="Code permissions" />
      </branch>
    </branch>
    <branch name="Scripting Languages">
      <branch name="Python">
        <branch link="http://docs.python.org/tut/tut.html" name="Tutorial" />
        <branch link="http://pyxml.sourceforge.net/topics/docs.html" name="XML Documentation" />
        <branch link="http://pyxml.sourceforge.net/topics/" name="XML Processing" />
        <branch link="http://pyxml.sourceforge.net/topics/howto/xml-howto.html" name="XML HOWTO" />
        <branch link="http://zephyrfalcon.org/labs/python_pitfalls.html" name="Pitfalls" />
      </branch>
      <branch name="Windows">
        <branch link="http://www.sysinternals.com" name="SysInternals" />
      </branch>
    </branch>
    <branch name="SQL References">
      <branch name="General">
        <branch link="http://www.mysql.com/" name="My SQL" />
        <branch link="http://www.oracle.com/" name="Oracle" />
        <branch link="http://www.postgresql.org/" name="PostgreSQL" />
      </branch>
      <branch name="PL/SQL">
        <branch link="http://www.orafaq.com/faqplsql.htm#WRAP" name="Oracle PL/SQL FAQ" />
      </branch>
    </branch>
    <branch name="WWW References">
      <branch link="http://www.w3.org/" name="World Wide Web Consortium (W3C)" />
      <branch link="http://www.w3.org/TR/REC-html40/" name="HTML 4.01 Specification" />
      <branch link="http://zvon.org/xxl/CSS2Reference/Output/index.html" name="CSS 2" />
      <branch link="http://www.w3schools.com/" name="W3Schools" />
      <branch link="http://geocities.yahoo.com/v/res/meg.html" name="Meta Tag Generator" />
    </branch>
    <branch name="Prolog References">
      <branch link="other/prologfun.txt" name="Prolog Functions" />
      <branch link="http://c2.com/cgi/wiki?PrologLanguage" name="Prolog Language" />
    </branch>
    <branch name="Lisp References">
      <branch link="http://clisp.cons.org/impnotes.html" name="GNU CLISP" />
      <branch link="http://www.apl.jhu.edu/~hall/lisp.html" name="Introduction and Tutorial" />
      <branch link="http://www.csee.umbc.edu/331/resources/lisp/LISP-tutorial.html" name="Common LISP Hints" />
    </branch>
    <branch name="Networking">
